# Generated by Django 4.0 on 2021-12-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_comment_listing_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comments',
            field=models.TextField(max_length=512),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Home', 'Home'), ('Electronics', 'Electronics'), ('Toys', 'Toys'), ('Fashion', 'Fashion')], max_length=32),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(max_length=512),
        ),
    ]
