# Generated by Django 4.0 on 2021-12-28 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_listing_img_listing_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='image_URL',
            new_name='image',
        ),
    ]
