# Generated by Django 4.0 on 2021-12-28 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_listing_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='bids',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comments',
        ),
        migrations.AddField(
            model_name='bid',
            name='bid',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bid',
            name='listing',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='current_bid', to='auctions.listing'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='starting_bid',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
