# Generated by Django 4.0 on 2021-12-28 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_remove_bid_bids_remove_comment_comments_bid_bid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='starting_bid',
        ),
        migrations.AddField(
            model_name='listing',
            name='bid',
            field=models.ForeignKey(default=0.0, on_delete=django.db.models.deletion.CASCADE, to='auctions.bid'),
        ),
    ]
