# Generated by Django 4.0 on 2021-12-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_remove_listing_bid_bid_listing_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='highest_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='starting_bid',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
    ]
