# Generated by Django 4.0 on 2021-12-31 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_listing_highest_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='comments',
            field=models.CharField(default='No comments.', max_length=512),
        ),
    ]
