# Generated by Django 4.0 on 2022-01-02 03:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_rename_listing_id_bid_listing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='users',
            field=models.ManyToManyField(related_name='watchlisted', to=settings.AUTH_USER_MODEL),
        ),
    ]
