# Generated by Django 4.0 on 2022-01-02 16:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_listing_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='users',
            field=models.ManyToManyField(null=True, related_name='watchlisted', to=settings.AUTH_USER_MODEL),
        ),
    ]
