# Generated by Django 4.0 on 2022-01-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_alter_bid_bid_alter_bid_user_alter_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Home', 'Home'), ('Electronics', 'Electronics'), ('Books', 'Books'), ('Toys', 'Toys'), ('Fashion', 'Fashion')], max_length=32),
        ),
    ]
